### ISSUE TITLE
I got this bug after my Flint Pickaxe is broken. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [BlueStaggo/divergent-progression#4]
![image](https://github.com/user-attachments/assets/2cafa213-84aa-458a-9142-4bc554bc79b4)

**Comment by BlueStaggo** [comment]
Definitely some incompatibility issue because this does not happen in vanilla. Keep disabling different mods while breaking tools until you find the one that causes the issue and let me know about it.

**Comment by makumaku1974** [comment]
> Definitely some incompatibility issue because this does not happen in vanilla. Keep disabling different mods while breaking tools until you find the one that causes the issue and let me know about it.

For sure. But I think you could either disable the replace method since it could produce problems with other mods. What I could recommend maybe is a config that disable or enable "tools wont break" with mod menu.

**Comment by makumaku1974** [comment]
damn, I got caught set_entity_data which is giving yourself a broken flint pickaxe and crashed the world. Which is you cant go back playing on the damn world and it needs to disable diverse progression again.

**Comment by makumaku1974** [comment]
[23:33:08] [Server thread/INFO]: [Maku: Gave 1 [Flint Pickaxe] to Maku]
[23:33:08] [Netty Local Client IO #0/INFO]: Disconnected from server, resetting proxy config values
[23:33:08] [Netty Server IO #1/ERROR]: Error sending packet clientbound/minecraft:container_set_slot
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_slot'
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[client-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[client-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9304.method_57534()" because the return value of "net.minecraft.class_1799.method_57824(net.minecraft.class_9331)" is null
	at eu.pb4.polymer.core.api.item.PolymerItemUtils.isPolymerServerItem(PolymerItemUtils.java:308) ~[polymer-core-0.9.9+1.21-b2ad175da92e9bfe.jar:?]
	at eu.pb4.polymer.core.api.item.PolymerItemUtils.getPolymerItemStack(PolymerItemUtils.java:152) ~[polymer-core-0.9.9+1.21-b2ad175da92e9bfe.jar:?]
	at net.minecraft.class_1799$1.localvar$dka000$polymer-core$polymer$replaceWithVanillaItem(class_1799.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799$1.method_56100(class_1799.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799$1.encode(class_1799.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_2653.method_55871(class_2653.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$6.encode(class_9139.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[client-intermediary.jar:?]
	... 31 more
[23:33:08] [Netty Server IO #1/ERROR]: Error sending packet clientbound/minecraft:system_chat
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:system_chat'
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[client-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[client-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9304.method_57534()" because the return value of "net.minecraft.class_1799.method_57824(net.minecraft.class_9331)" is null
	at eu.pb4.polymer.core.api.item.PolymerItemUtils.isPolymerServerItem(PolymerItemUtils.java:308) ~[polymer-core-0.9.9+1.21-b2ad175da92e9bfe.jar:?]
	at eu.pb4.polymer.core.api.item.PolymerItemUtils.getPolymerItemStack(PolymerItemUtils.java:152) ~[polymer-core-0.9.9+1.21-b2ad175da92e9bfe.jar:?]
	at eu.pb4.polymer.core.api.item.PolymerItemUtils.getPolymerItemStack(PolymerItemUtils.java:136) ~[polymer-core-0.9.9+1.21-b2ad175da92e9bfe.jar:?]
	at net.minecraft.class_1799.mddc69a7$polymer-core$lambda$patchCodec$1$2(class_1799.java:6142) ~[client-intermediary.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$RecursiveCodec.encode(Codec.java:217) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.lambda$encode$3(EitherCodec.java:34) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:33) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:11) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.MapCodec$2.encode(MapCodec.java:82) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:74) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:163) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.lambda$encode$3(EitherCodec.java:34) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:33) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:11) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.OptionalFieldCodec.encode(OptionalFieldCodec.java:44) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.OptionalFieldCodec.encode(OptionalFieldCodec.java:17) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:295) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:297) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:163) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.lambda$encode$4(EitherCodec.java:35) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:33) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:11) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$RecursiveCodec.encode(Codec.java:217) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.lambda$encode$4(EitherCodec.java:35) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:33) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:11) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.ListCodec.encode(ListCodec.java:36) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.ListCodec.encode(ListCodec.java:17) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.OptionalFieldCodec.encode(OptionalFieldCodec.java:44) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.OptionalFieldCodec.encode(OptionalFieldCodec.java:17) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:297) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.class_8824$class_8825.encode(class_8824.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_8824$Anonymous$47709dd217ec495ca1d79e7820c9d889.encode(TextCodecsMixin.java:65) ~[?:?]
	at net.minecraft.class_8824$class_8912.encode(class_8824.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_5699$3.encode(class_5699.java:234) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:295) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:163) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.lambda$encode$4(EitherCodec.java:35) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:33) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:11) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$RecursiveCodec.encode(Codec.java:217) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.class_9135$6.method_56902(class_9135.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.class_9135$6.encode(class_9135.java:268) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$12.encode(class_9139.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[client-intermediary.jar:?]
	... 31 more
[23:33:08] [Server thread/INFO]: Maku lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_entity_data'
[23:33:08] [Server thread/INFO]: Maku left the game
[23:33:08] [Render thread/INFO]: Xaero hud session finalized.
[23:33:08] [Render thread/INFO]: Finalizing world map session...
[23:33:08] [Thread-4/INFO]: World map force-cleaned!
[23:33:08] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:33:08] [Server thread/INFO]: Stopping server
[23:33:08] [Server thread/INFO]: Saving players
[23:33:08] [Server thread/INFO]: Saving worlds
[23:33:08] [Render thread/INFO]: World map session finalized.
[23:33:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newborn Manly]'/minecraft:overworld
[23:33:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newborn Manly]'/minecraft:the_nether
[23:33:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newborn Manly]'/minecraft:the_end
[23:33:11] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Newborn Manly]'/eternal_starlight:starlight
[23:33:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (Newborn Manly): All chunks are saved
[23:33:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:33:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:33:11] [Server thread/INFO]: ThreadedAnvilChunkStorage (starlight): All chunks are saved
[23:33:11] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:33:12] [Render thread/INFO]: Stopping worker threads
[23:33:12] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_entity_data'

**Comment by makumaku1974** [comment]
This one is the latest.

[00:08:14] [Netty Server IO #3/ERROR]: Error sending packet clientbound/minecraft:container_set_slot
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_slot'
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[client-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[client-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
[00:08:14] [Netty Local Client IO #1/INFO]: Disconnected from server, resetting proxy config values
[00:08:14] [Server thread/INFO]: Maku lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_slot'

**Comment by makumaku1974** [comment]
I found the problem I hope.

**Comment by makumaku1974** [comment]
Im reporting it to diversity. I'll reopen if issues starts to begin again.
